{
 "title": "Zigbee2MQTT Ultimate",
 "tags": [
  "zigbee2mqtt",
  "climate",
  "safety"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperatures - Zigbee2MQTT",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "T1 Korytarz Warszt",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't1_korytarz_warszt_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T2 W4",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't2_w4_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T3 W5 Laser",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't3_w5_laser_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T4 Patryk Biuro",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't4_patryk_biuro_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T5 Bartek",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't5_bartek_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T6 Pompownia",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't6_pompownia_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T7 Kotlownia",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't7_kotlownia_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T8 Dostawka",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't8_dostawka_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T9 Patryk Hall",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't9_patryk_hall_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T10 Rodzice Dol",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't10_rodzice_dol_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T12 Garaz",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't12_garaz_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T14 Suszarnia Konwencjonalna",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't14_suszarnia_konwencjonalna_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T15 Malarnia",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't15_malarnia_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T15 Salon Patryk",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't15_salon_patryk_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T18 Gora Rodzice",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't18_gora_rodzice_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T20 W3",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't20_w3_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "TO1 Kimla",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 'to1_kimla_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Temperatures - Zigbee2MQTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "T1 Korytarz Warszt",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't1_korytarz_warszt_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T2 W4",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't2_w4_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T3 W5 Laser",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't3_w5_laser_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T4 Patryk Biuro",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't4_patryk_biuro_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T5 Bartek",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't5_bartek_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T6 Pompownia",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't6_pompownia_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T7 Kotlownia",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't7_kotlownia_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T8 Dostawka",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't8_dostawka_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T9 Patryk Hall",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't9_patryk_hall_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T10 Rodzice Dol",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't10_rodzice_dol_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T12 Garaz",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't12_garaz_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T14 Suszarnia Konwencjonalna",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't14_suszarnia_konwencjonalna_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T15 Malarnia",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't15_malarnia_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T15 Salon Patryk",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't15_salon_patryk_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T18 Gora Rodzice",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't18_gora_rodzice_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "T20 W3",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 't20_w3_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "TO1 Kimla",
     "query": "SELECT mean(\"value\") FROM \"°C\" WHERE (\"entity_id\"::tag = 'to1_kimla_temperature') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Humidity - Zigbee2MQTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Laser G01",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE \"entity_id\"::tag = 't3_w5_laser_humidity' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Rodzice G02",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't18_gora_rodzice_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Biuro G02",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't4_patryk_biuro_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Warsztat G03",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't1_korytarz_warszt_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Pompownia G03",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't6_pompownia_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "W4",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't2_w4_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Malarnia",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't15_malarnia_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Garaz",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't12_garaz_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Bartek",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't5_bartek_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Salon Patryk",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\"::tag = 't15_salon_patryk_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Na zewnątrz (Kimla)",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE \"entity_id\"::tag = 'to1_kimla__humidity' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Pressure - Zigbee2MQTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "hectopascal" } },
   "targets": [
    {
     "alias": "Laser",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE \"entity_id\"::tag = 't3_w5_laser_pressure' AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Rodzice",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't18_gora_rodzice_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Biuro",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't4_patryk_biuro_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Warsztat",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't1_korytarz_warszt_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Pompownia",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't6_pompownia_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "W4",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't2_w4_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Malarnia",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't15_malarnia_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Garaz",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't12_garaz_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Bartek",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't5_bartek_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Salon",
     "query": "SELECT mean(\"value\") FROM \"hPa\" WHERE (\"entity_id\"::tag = 't15_salon_patryk_pressure') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Hargassner - Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Boiler temp",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_piec_temp') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Flue temp",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_spaliny_temp') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Buffer top",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_acc_temp_top') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Buffer center",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_acc_temp_center') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Buffer bottom",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_acc_temp_bottom') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Hot water",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_hwt') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Circuit home",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_obieg_dom') AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Circuit workshop",
     "query": "SELECT mean(\"value\") FROM \"\\u00b0C\" WHERE (\"domain\"::tag = 'sensor' AND \"entity_id\"::tag = 'panna_obieg_warsztat') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}