{
 "title": "Zigbee2MQTT - Batteries",
 "tags": [
  "zigbee2mqtt",
  "battery"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Temperature/Humidity sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery level - Temperature/Humidity sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "t10_rodzice_dol_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't10_rodzice_dol_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t12_garaz_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't12_garaz_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t14_suszarnia_konwencjonalna_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't14_suszarnia_konwencjonalna_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t15_malarnia_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't15_malarnia_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t15_salon_patryk_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't15_salon_patryk_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t1_korytarz_warszt_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't1_korytarz_warszt_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t20_w3_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't20_w3_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t2_w4_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't2_w4_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t3_w5_laser_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't3_w5_laser_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t5_bartek_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't5_bartek_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t6_pompownia_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't6_pompownia_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t7_kotlownia_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't7_kotlownia_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t8_dostawka_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't8_dostawka_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "t9_patryk_hall_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 't9_patryk_hall_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "to1_kimla_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'to1_kimla_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  { "title": "Smoke detectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Battery level - Smoke detectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "s2_patryk_dom_korytarz_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's2_patryk_dom_korytarz_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s3_garaz_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's3_garaz_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s4_malarnia_smoke_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's4_malarnia_smoke_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s5_warsztat_schody_ga3ra_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's5_warsztat_schody_ga3ra_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s6_korytarz_warsztat_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's6_korytarz_warsztat_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s7_w4_6ax_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's7_w4_6ax_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s8_bartek_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's8_bartek_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "s9_rodzice_gora_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 's9_rodzice_gora_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  { "title": "Motion/Illuminance sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Battery level - Motion/Illuminance sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "m1_rodzice_dol_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'm1_rodzice_dol_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "m2_garaz_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'm2_garaz_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "m2_salon_patryk_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'm2_salon_patryk_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "m4_galeria_2_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'm4_galeria_2_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "m5_bartek_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'm5_bartek_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  { "title": "Contacts/Gates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Battery level - Contacts/Gates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "c1_w5_brama_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'c1_w5_brama_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "c2_w4_brama_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'c2_w4_brama_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "c4_dostawka_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'c4_dostawka_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  { "title": "Other Zigbee devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Battery level - Other Zigbee devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "0x54ef441001243bcf_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = '0x54ef441001243bcf_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "0xa4c13822b76ad085_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = '0xa4c13822b76ad085_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "b1_korytarz_warsztat_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'b1_korytarz_warsztat_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "b2_malarnia_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'b2_malarnia_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "f1_pompownia_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'f1_pompownia_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "alias": "f2_kotlownia_battery",
     "query": "SELECT last(\"value\") FROM \"percent\" WHERE (\"entity_id\"::tag = 'f2_kotlownia_battery') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  }
 ]
}